openapi: 3.0.3
info:
  title: Address search operations
  description: |
    This api is used by the Associate App to search and complete addresses
  version: 1.0.0
  x-audience: internal-company
  x-api-id: address-completion
  contact:
    name: Team Mobile Platform
    url: https://www.newstore.com
    email: team-mobile-platform@newstore.com
  x-domain-gateway-integration:
    serviceName: address-completion
    lambda:
      arn: >-
        arn:aws:lambda:{{.region}}:{{.target_account}}:function:address-ninja-prod-completion
servers:
  - url: https://{tenant}.p.newstore.net/retail-org/address-completions/addresses
  - url: https://retail-org.p.newstore.domains/address-completions/addresses
tags:
  - name: Address completion
    description: Address completion
paths:
  /address-completions/addresses:
    get:
      operationId: listAddresses
      description: Completes addresses to structured results from query input
      summary: Completes addresses to structured results
      tags:
        - Address completion
      security:
        - oauth2:
            - address-completion:completion:read
      parameters:
        - in: path
          name: query
          schema:
            type: string
          required: true
        - in: path
          name: context
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Found address result.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompletionResponse'
        '400':
          description: Bad request.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '404':
          description: Not found.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        default:
          description: Unexpected error.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ValidationError'
components:
  schemas:
    ValidationError:
      type: object
      required:
        - status_code
        - error
      properties:
        status_code:
          type: integer
          description: HTTP status code
          format: int32
          example: 500
        error:
          type: string
          description: Error message
          example: Internal server error
    CompletionRequest:
      type: object
      properties:
        query:
          type: string
    CompletionResponse:
      type: object
      properties:
        address_line_1:
          type: string
          description: Address line 1
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        password:
          tokenUrl: /v0/token
          scopes:
            address-completion:completion:read: Complete address
