openapi: 3.0.0
info:
  title: Data provisioning Graphql query API
  description: >-
    Data provisioning query service implemented as a GraphQL endpoint to expose
    data to integrations
  version: 2020-1
servers:
  - url: https://dodici.x.newstore.net/api/v1/org/data
paths:
  /query:
    post:
      responses:
        '200':
          description: The GraphQL query result.
        '500':
          description: Internal server error.
      description: >
        This endpoint provides flexible query facilities for selected platform
        entities, such as orders,  fulfillment requests, and payment
        transactions. The GraphQL query schema of this endpoint is  provided via
        the [GraphiQL Schema Explorer](/docs/graphiql/graphiql.html).  For more
        information, see the [GraphQL
        API](/docs/development/api/graphql-api.html) page.
      summary: Execute GraphQL queries
      operationId: graphqlQuery
components:
  securitySchemes:
    newStoreAccessToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
x-annotation-crossOriginAllowed: true
